apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-8pfl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-8pfl
    app.kubernetes.io/part-of: ci1t-830-0005-app
  name: devfile-sample-8pfl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-8pfl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-8pfl
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0005-tenant/ci1t-830-0005-app/devfile-sample-8pfl@sha256:ca328340df4b68e4555e27a93878e12c81323d58cea26dc2388ce73061a0f65e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
